FROM    centos:centos6

RUN	yum install -y wget which tar unzip nc 

RUN	wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz"
RUN	tar xvf jdk-8u45-linux-x64.tar.gz
ENV	JAVA_HOME $HOME/jdk1.8.0_45

RUN	wget http://repo.spring.io/libs-snapshot-local/org/springframework/xd/spring-xd/1.2.0.BUILD-SNAPSHOT/spring-xd-1.2.0.BUILD-20150423.001857-1-dist.zip
RUN 	unzip spring-xd-1.2.0.BUILD-20150423.001857-1-dist.zip

ENV 	XD_BASE $HOME/spring-xd-1.2.0.BUILD-SNAPSHOT
ENV	XD_HOME $XD_BASE/xd

ENV	PATH $PATH:$XD_HOME/bin:$XD_BASE/shell/bin:$JAVA_HOME/bin

RUN	echo PATH=$PATH

# Bundle source
COPY 	streaming streaming
COPY	prediction prediction

EXPOSE	9393
